### ISSUE TITLE
Running list of transformer issues / questions (warning: SUPER NITPICKY!)

### ISSUE THREAD

**Issue by retabak** [P-bibs/codap-transformers#239] opened 2022-03-31 14:59 UTC
A months-long break from CODAP has enabled me to look at the Transformer UI and its functionality with fresh eyes. I'm dumping in this git issue *everything* that comes to mind as a possible improvement. 

- [x] Transform Attribute. This Transformer should ask for the name of the new attribute (just like how Build Attribute does). If you're converting feet to inches or ages to old / young, you likely want the attribute name to indicate the transformation that has occurred. (The lesson could prompt students to change the name manually, but that seems like an unneeded extra step that the Transformer could do automatically.) 
- [x] Redundancy / helpfulness of language. I see that the boxes where students type are either blank or they have the same text that is above the box. (Update - @thomascastleman had the same idea before me!)
- For instance, “Transformer Name” is written above the box where students type _and_ inside of it. Can we put some helper text in the boxes, instead?  
- For Transformer Name, “i.e. order-by-weight” or “i.e. filter-is-cat” would be great. (This would be even more valuable if the helper text corresponded with the specific Transformer.)
- Inside the “Purpose Statement”” box, it just says “Purpose Statement” again. What if we put, “What does the formula do for each row?”
- Maybe in the expression box we could add an example of an expression also?
- [x] *BUG*. Error messages. They're not always appearing for incorrect contracts. See example below. (There are others.)
![unnamed](https://user-images.githubusercontent.com/87144723/161083079-621a0b56-962f-410f-be01-c10ccfcb7c94.png)
- [x] Inconsistent language. There’s some inconsistency in the language used on the UI  for different transformers. See yellow highlights on the screenshot below. Namely, “filter” says “How to Filter” but Transform and Build say “Formula for…” ? (And “Sort” says “Key expression” in this same position.) Can we be consistent? Or, alternatively, is there a reason we’re not being consistent? 
![unnamed (1)](https://user-images.githubusercontent.com/87144723/161083286-63294987-7b0e-4886-92ef-ccea076a98bf.png)
- [x] Language in “Sort.” The wording here is confusing: “Sort the rows in this dataset by a value, which is computed by:” In many instances, students will just put an attribute as the expression. I think the wording makes more sense when students put something like `stringLength(Name)`. (Is this just me being confused? That's possible.) UPDATE - PR posted a few weeks ago resolves this.
- [x] Documentation needs to be updated to match with updates to UI.
- [x] Save button. Clicking “save this transformer” makes a button appear that just says “save.” Why does it take two clicks to save and not just one? (I expected options to appear when I selected “Save this transformer.”) UPDATE: Just noticed that @thomascastleman had the same feedback. 
- [x] *BUG* Save functionality / need more error messages? If I attempt to save the very same transformer a few times in a row, CODAP just saves it AGAIN without changing the name / adding to the name / prompting me to change the name. Then, if I modify the transformer, CODAP saves it yet again without prompting me to change the name. So, that means CODAP is okay with me having two transformers with the very same name that do totally different things.
- [ ] Save functionality. Wouldn’t it be cool if the Transformers that were named and saved showed up on the drop-down list of Transformers? So like, instead of seeing this:	

Constructing:
- Build Attribute
- Transform Attribute
- Filter
- Sort

Students would see this:

Constructing:
- Build Attribute
-- build-heavy
- Transform Attribute
- Filter
- Sort
-- order-by-name
-- order-by-weight

Right now saved transformers are kind of just flying all over the place. I know kids can organize them on screen, but it seems like it might be nice to have them appear on the menu (or somewhere more structured) if possible. Maybe a pipe dream?

**Comment by schanzer** [comment] 2022-04-11 15:05
Amen on the desire to have a place where kids can bring those transformers back! A kid on a 9" chromebook is going to have a hard time with all those transformer windows!

**Comment by retabak** [comment] 2022-04-27 17:22
Thanks to some nudging from @schanzer and Shriram, I'm updating this issue....

First - if you've got a minute, check out some of the (in-progress) Bootstrap lessons / worksheets using Transformers! 

[Intro to Transformers](https://github.com/P-bibs/codap-transformers/files/8574951/Introduction.to.Transformers_.Sort.pdf) + [an accompanying worksheet](https://github.com/P-bibs/codap-transformers/files/8574952/codap-sort-transformer.pdf)
[More Transformers (Filter, Transform, Build)](https://github.com/P-bibs/codap-transformers/files/8574931/Transformers_.Filter.Transform.Build.pdf)
[Method Chaining](https://github.com/P-bibs/codap-transformers/files/8574932/Method.Chaining.pdf) + [an accompanying worksheet](https://github.com/P-bibs/codap-transformers/files/8574953/chaining-methods.pdf)

This is just a taste of the instruction made possible thanks to your amazing work. Thanks for being so responsive to all of very specific needs relating to the Design Recipe, error messages, compatibility with Pyret, and on and on.

And, here's an abberviated, more organized / prioritized version of the nitpicky list posted earlier in this git issue (no screenshots this time and far less detail, but much easier to read / process - hopefully!):

**ESSENTIAL**
- [ ] Need error messages to appear when incorrect contracts are entered.
- [ ] Don’t allow users to save two Transformers with the same name.
- [ ] Update documentation to match updates to Transformers.

**IMPORTANT**
- [ ] Transform Attribute should prompt users to provide new attribute name
- [ ] Allow users to bring Transformers back after closing / store saved Transformers somewhere accessible (not just as Transformer windows).
 
**NICE TO HAVE**
- [ ] Put helper text in boxes where students type
- [ ] Be consistent with language on UI for different Transformers
- [ ] Saving should take one click, not two.

**Comment by thomascastleman** [comment] 2022-05-26 19:21
@retabak Most of these items are coming along well, but I wanted to note that the lack of errors from certain incorrect contracts stems from our reliance on native CODAP's functions for type checking instead of our own (see the discussion in #227). The conclusion there was to stick with using CODAP's functions but document our complaints (which I don't think has happened yet - we can get to work on that).

Also, on the item of "bringing Transformers back after closing", it's true that if you close a Transformer with the X button, it will go away forever, but you can also use the minimize button (the minus sign pictured below in the top right of the blue bar) to make the Transformer window very small (something which could be very useful for conserving screen space)
![minimize-button](https://user-images.githubusercontent.com/13399527/170556862-fb140bc4-6c31-44f1-af3a-4c1736ae3594.png)
![minimized](https://user-images.githubusercontent.com/13399527/170558601-49495a36-c92b-46f6-9ba2-8eecd329215c.png)

The reason the two buttons are separate is because we wanted more control over behavior when you try to close the Transformer - we currently warn you it will disappear, *but only if the Transformer has already been used to produce some output datasets*. **Should we instead *always* warn and maybe add a suggestion that users use the minimize button instead in that warning?**

And lastly, it's worth noting that all active Transformers (that haven't been deleted) can be found by clicking the Tiles button at the top right of CODAP:
![tiles-menu](https://user-images.githubusercontent.com/13399527/170558012-bb04f0ab-406b-4129-ab2a-f686d6d04ec5.png)
Tiles just lists pretty much every element you have in your workspace, so saved Transformers are mixed in with datasets and other plugins being used, but are there nonetheless. When you click on them in this menu, they are brought to the foreground and un-minimized - I could definitely see these features being used to manage having a lot of Transformers on a small screen.

**Comment by schanzer** [comment] 2022-05-26 23:35
@thomascastleman thanks for this. I had no idea you could access closed Transformers from the tiles menu! Very helpful.

I think showing that warning whether or not a Transformer has been saved is a good idea.

Re: type-checking -- I hear you on the need to rely on CODAP sketchy type system for now. Can you confirm that we DO get errors when the type system catches them, though? From Rachel's comment, it sounds like we don't get _any_ errors.

**Comment by retabak** [comment] 2022-05-27 12:27
Thanks, @thomascastleman !

Regarding errors - they sometimes appear, and sometimes not. I am not savvy enough to know which error messages are in our control and which ones are not, or I'd provide more specific feedback. 

I like the idea of a warning message + suggestion. 

Also, wow, I totally did not realize that's what the Tiles button was for.  I feel silly! I think in my head, I wanted the Tiles button to organize everything in the workspace (like - to visually _tile_ all of the datasets and plugins and such). After discovering that it did not do that, I tuned it out. Good to know that there is a way for students to attempt to stay organized.

**Comment by thomascastleman** [comment] 2022-05-27 15:34
@schanzer @retabak Yes, I can confirm that we get errors when the CODAP type predicates tell us that a value in a column doesn't match the type written in the contract. For instance, performing a Build Attribute with a formula contract of Row -> Boolean but providing String values:
![type-error](https://user-images.githubusercontent.com/13399527/170721810-5c71ed47-ab74-4149-87fb-b32ce5a66679.png)
This is because their `isBoolean` predicate is relatively strict, allowing only actual booleans and the strings `"true"` and `"false"`. The cases where we don't get errors are due to the CODAP predicates not behaving as we'd like.

And sounds good, we can make sure to warn anytime a user tries to close a Transformer.

**Comment by retabak** [comment] 2022-06-14 15:01
I think this issue can be closed? Will let one of you do the honors.

I'm going to open a new one with some other little concerns.

**Closed** 2022-06-15 00:07 UTC
